pipelines:
  branches:
    develop:
      - step:
          name: First Pipeline!
          script:
            - echo "Hello world"
          #name: Deploy Plugin Update to Cornershop Plugin Recovery site
          #script:
            #- pipe: atlassian/sftp-deploy:0.6.0
            #  USER: 'cshpplugins'
            #  SERVER: '35.245.17.148'
            #  PASSWORD:
            #  EXTRA_ARGS: '-Port=16469'