pipelines:
  branches:
    develop:
      - step:
          name: Deploy Plugin Update to Cornershop Plugin Recovery site
          script:
            - pipe: atlassian/sftp-deploy:0.6.0
              variables:
                USER: 'cshpplugins'
                SERVER: '35.245.17.148'
                EXTRA_ARGS: '-oPort=16469'
                REMOTE_PATH: 'public/wp-content/plugins/cshp-plugin-tracker'
                DEBUG: 'true'